Reland "libdot: require Python 3.5+ up front"
This is safe to reland as CrOS has switched `python3` to 3.6 now.

We're only testing against Python 3.5 or newer currently, and we're
using features added in that release, so make we're running it.  This
will help avoid confusing errors like:
  File ".../libapps/libdot/bin/libdot.py", line 135, in run
    result = subprocess.run(cmd, cwd=cwd, **kwargs)
AttributeError: 'module' object has no attribute 'run'

Change-Id: I17a89da800ab72532c689ac14ad958302081f005
Reviewed-on: https://chromium-review.googlesource.com/c/apps/libapps/+/1725326
Reviewed-by: Joel Hockey <joelhockey@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>