Revert "libdot: require Python 3.5+ up front"
This reverts commit e6057dff36ce36494180fbeb6edafae99624538b.

Reason for revert: broke the tree https://ci.chromium.org/p/chromeos/builders/general/CommitQueue/b8910564816969468848

Original change's description:
> libdot: require Python 3.5+ up front
> 
> We're only testing against Python 3.5 or newer currently, and we're
> using features added in that release, so make we're running it.  This
> will help avoid confusing errors like:
>   File ".../libapps/libdot/bin/libdot.py", line 135, in run
>     result = subprocess.run(cmd, cwd=cwd, **kwargs)
> AttributeError: 'module' object has no attribute 'run'
> 
> Change-Id: I1e31ad04faf85dc7e94606e8106973f1fe950f2d
> Reviewed-on: https://chromium-review.googlesource.com/c/apps/libapps/+/1660837
> Reviewed-by: Joel Hockey <joelhockey@chromium.org>
> Tested-by: Mike Frysinger <vapier@chromium.org>

TBR=vapier@chromium.org,joelhockey@chromium.org

Change-Id: I17fb3860acc0080dae4a0eca120c49ca3b789745
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/apps/libapps/+/1661750
Reviewed-by: Jason Clinton <jclinton@chromium.org>
Tested-by: Jason Clinton <jclinton@chromium.org>